export class Constant {
    public static availableCities: any = [
        "Belo Horizonte",
        "Raleigh",
        "Suzhou",
        " Angers",
        " Bad Honnef",
        " Bordeaux",
        " Brazil",
        " Budapest",
        " Caen",
        " Hamburg",
        " Le Havre",
        " Lyon",
        " Nancy",
        " Niort",
        " Paris",
        " Tours",
        "Angers",
        "Angoulême",
        "Bad Honnef",
        "Barcelona",
        "Belo Horizonte",
        "Belo Horizonte (Brazil)",
        "Berlin",
        "Berlin, Bad Honnef",
        "Bordeaux",
        "Brest",
        "Budapest",
        "Caen",
        "Cergy",
        "Clermont-Ferrand",
        "Cognac",
        "DRESDEN",
        "HAMBURG",
        "Hamburg",
        "Hanoi",
        "Iserlohn",
        "La Rochelle",
        "Le Havre",
        "Lille",
        "Lille",
        "Lisbon",
        "Lyon",
        "Marseille",
        "Montpellier",
        "Nancy",
        "Nantes",
        "Nantes ",
        "Nice",
        "Niort",
        "Nuremberg",
        "Oxford",
        "Paris",
        "Paris",
        "Paris ",
        "Raleigh",
        "Raleigh",
        "Raleigh (USA) ",
        "Reims",
        "Rennes",
        "Rochefort",
        "Rouen",
        "Shanghai",
        "Singapore",
        'Sophia-Antipolis',
        "Sophia-Antipolis",
        "Sophia-Antipolis",
        "Sophia-Antipolis (France)",
        "Strasbourg",
        "Suzhou",
        "Toulon",
        "Toulouse",
        "Toulouse ",
        "Tours",
    ];

    public static availableFields: any = [
        "Business & Management",
        "Artificial Intelligence ",
        "Arts, Design & Architecture Business & Management",
        "Business & Management Aeronautic",
        "Business & Management Artificial Intelligence Business Analytics",
        "Business & Management Finance",
        "Business & Management Luxury, Fashion",
        "Business & Management Marketing",
        "Business & Management Supply Chain",
        "Computer Engineering ",
        "Computer Science & IT",
        "Data science",
        "Engineering",
        "Engineering & Technology",
        "Finance",
        "Hospitality, tourism Business & Management ",
        "International Business",
        "Nuclear Engineering, Environemental",
        "Supply Chain",
        "Technology",

    ];

    public static availableSchools: any = [
        'AUDENCIA',
        'ECAM Lyon',
        'EISTI',
        'EM NORMANDIE',
        'EPITA',
        'ESAIP',
        'ESC CLERMONT',
        'ESSCA',
        'ESSEC',
        'EXCELIA',
        'ICN',
        'IESEG',
        'IMT Atlantique',
        'IPAG',
        'ISEP',
        'IUBH',
        'KEDGE BS',
        'Montpellier BS',
        'NEOMA',
        'Nova SBE',
        'PARIS SCHOOL OF BUSINESS',
        'RENNES BUSINESS SCHOOL',
        'SKEMA',
        'SRH : Germany',
        'TOULOUSE BUSINESS SCHOOL',
        'UE Germany',
    ];
}